# -*- coding: utf-8 -*-
"""3D Bandlet Smoke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4WlccENCEa5ULM3BJmVBgUM1ai5Kokd
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AngshulMajumdar/3D-Bandlet-Transform.git /content/3D-Bandlet-Transform

# %cd /content/3D-Bandlet-Transform

import sys, os
sys.path.insert(0, "/content/3D-Bandlet-Transform")

print("repo root exists:", os.path.exists("/content/3D-Bandlet-Transform"))
print("top-level contents:", os.listdir("/content/3D-Bandlet-Transform"))

from bandlet_tf3d import __version__
from bandlet_tf3d.config3d import Bandlet3DConfig
from bandlet_tf3d.transform3d import BandletTransform3D

print("version:", __version__)
print("imports passed")

import torch
from bandlet_tf3d.config3d import Bandlet3DConfig
from bandlet_tf3d.transform3d import BandletTransform3D

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

cfg = Bandlet3DConfig(
    levels=2,
    block_size=4,
    device=device,
    dtype="float32",
)

T = BandletTransform3D(cfg).to(device)

x = torch.randn(1, 1, 16, 16, 16, device=device)
enc = T.encode(x)
xrec = T.reconstruct(enc)

if device == "cuda":
    torch.cuda.synchronize()

rel_err = (x - xrec).norm() / (x.norm() + 1e-12)
max_abs = (x - xrec).abs().max()

print("PR relative error =", float(rel_err.detach().cpu()))
print("PR max abs error  =", float(max_abs.detach().cpu()))
print("x shape:", tuple(x.shape))
print("xrec shape:", tuple(xrec.shape))

import torch
from bandlet_tf3d.config3d import Bandlet3DConfig
from bandlet_tf3d.transform3d import BandletTransform3D

device = "cuda" if torch.cuda.is_available() else "cpu"

cfg = Bandlet3DConfig(
    levels=2,
    block_size=4,
    device=device,
    dtype="float32",
)

T = BandletTransform3D(cfg).to(device)

x = torch.randn(1, 1, 16, 16, 16, device=device)

vec, meta = T.encode_packed(x)
xrec = T.decode_packed(vec, meta)

if device == "cuda":
    torch.cuda.synchronize()

rel_err = (x - xrec).norm() / (x.norm() + 1e-12)

print("Packed roundtrip relative error =", float(rel_err.detach().cpu()))
print("Packed vec shape:", tuple(vec.shape))
print("Meta keys:", sorted(list(meta.keys()))[:20])

import torch
from bandlet_tf3d.config3d import Bandlet3DConfig
from bandlet_tf3d.transform3d import BandletTransform3D

device = "cuda" if torch.cuda.is_available() else "cpu"

cfg = Bandlet3DConfig(
    levels=2,
    block_size=4,
    device=device,
    dtype="float32",
)

T = BandletTransform3D(cfg).to(device)

x = torch.randn(1, 1, 16, 16, 16, device=device, requires_grad=True)
enc = T.encode(x)
xrec = T.reconstruct(enc)
loss = ((xrec - x) ** 2).mean()
loss.backward()

if device == "cuda":
    torch.cuda.synchronize()

print("loss =", float(loss.detach().cpu()))
print("grad norm =", float(x.grad.norm().detach().cpu()))
print("grad has nan =", bool(torch.isnan(x.grad).any().detach().cpu()))

import runpy

runpy.run_path("/content/3D-Bandlet-Transform/examples/smoke_test.py", run_name="__main__")

import runpy

runpy.run_path("/content/3D-Bandlet-Transform/examples/smoke_test.py", run_name="__main__")